table T01_门店表
	lineageTag: edcfe645-a82d-49ce-b552-d3cc443748e4

	column F_00_自动编号
		dataType: int64
		formatString: 0
		lineageTag: a5156d16-0528-4805-a12f-77f7dacfe927
		summarizeBy: sum
		sourceColumn: F_00_自动编号

		annotation SummarizationSetBy = Automatic

	column F_01_门店编号
		dataType: string
		lineageTag: c6d82e7d-089e-439f-961a-222fd2fc1d1e
		summarizeBy: none
		sourceColumn: F_01_门店编号

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isText":true}

	column F_02_门店名称
		dataType: string
		lineageTag: 91d44a4b-a643-4a7f-bd89-f7b2b5c54aed
		summarizeBy: none
		sourceColumn: F_02_门店名称
		sortByColumn: F_01_门店编号

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isText":true}

	column F_03_门店负责人
		dataType: string
		lineageTag: bc77f8e5-5bbb-4ff7-9142-d2a14188e775
		summarizeBy: none
		sourceColumn: F_03_门店负责人

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isText":true}

	column F_04_开店日期
		dataType: dateTime
		formatString: Long Date
		lineageTag: 074532c1-3317-4790-aee6-781e990501d0
		summarizeBy: none
		sourceColumn: F_04_开店日期

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Date

	column F_07_纬度
		dataType: double
		lineageTag: 8dd8ee18-3c73-41b8-82ff-c0b4ab115a2d
		dataCategory: Latitude
		summarizeBy: sum
		sourceColumn: F_07_纬度

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column F_08_经度
		dataType: double
		lineageTag: 36454739-02ef-4438-9cc9-575c10b96b5f
		dataCategory: Longitude
		summarizeBy: sum
		sourceColumn: F_08_经度

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column F_09_关店日期
		dataType: dateTime
		formatString: Long Date
		lineageTag: 8957bf81-29ca-4d20-b7aa-664ac2b5b06b
		summarizeBy: none
		sourceColumn: F_09_关店日期

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Date

	column F_05_城市ID
		dataType: int64
		formatString: 0
		lineageTag: 99e4bd80-6f1c-4e57-81c7-34b9e02b94ee
		summarizeBy: none
		sourceColumn: F_05_城市ID

		annotation SummarizationSetBy = Automatic

	column F_06_城市
		dataType: string
		lineageTag: d118f061-c28b-4614-86a1-3f9068e1600e
		summarizeBy: none
		sourceColumn: F_06_城市

		annotation SummarizationSetBy = Automatic

	partition T01_门店表-a2b89588-b9e3-42b0-87dd-81a03c523b84 = m
		mode: import
		source =
				let
				  源 = Csv.Document(File.Contents(Path&"\T01_门店表.csv"), [Delimiter = ",", Columns = 10, Encoding = 65001, QuoteStyle = QuoteStyle.None]),
				    提升的标题 = Table.PromoteHeaders(源, [PromoteAllScalars=true]),
				    更改的类型 = Table.TransformColumnTypes(提升的标题,{{"F_00_自动编号", Int64.Type}, {"F_05_城市ID", Int64.Type}, {"F_04_开店日期", type date}, {"F_09_关店日期", type date}, {"F_07_纬度", type number}, {"F_08_经度", type number}})
				in
				    更改的类型

	annotation PBI_ResultType = Table

	annotation PBI_NavigationStepName = 导航

