table T02_客户表
	lineageTag: 8146752b-a1b9-4901-9597-49dee67fcb20

	column F_00_自动编号
		dataType: int64
		formatString: 0
		lineageTag: 81730cde-d4b7-4a06-8ae1-af67d8371062
		summarizeBy: none
		sourceColumn: F_00_自动编号

		annotation SummarizationSetBy = Automatic

	column F_01_客户编号
		dataType: string
		lineageTag: eb0cda82-ef2d-4d40-bb83-fe824311b897
		summarizeBy: none
		sourceColumn: F_01_客户编号

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isText":true}

	column F_02_客户名称
		dataType: string
		lineageTag: 565ed43d-bfa2-4b7c-99b0-44804441ecb6
		summarizeBy: none
		sourceColumn: F_02_客户名称

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isText":true}

	column F_03_客户生日
		dataType: dateTime
		formatString: Long Date
		lineageTag: 3913cf45-9650-4c0a-a939-4f01fb3acbee
		summarizeBy: none
		sourceColumn: F_03_客户生日

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Date

	column F_04_客户性别
		dataType: string
		lineageTag: 15432815-e308-4571-afb3-5827756cae1c
		summarizeBy: none
		sourceColumn: F_04_客户性别

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isText":true}

	column F_05_注册日期
		dataType: dateTime
		formatString: Long Date
		lineageTag: 89ba13c6-8342-459d-92a4-a7cac225ec50
		summarizeBy: none
		sourceColumn: F_05_注册日期

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Date

	column F_06_客户行业
		dataType: string
		lineageTag: 7fde3445-3030-43ea-ac02-68a13f81838b
		summarizeBy: none
		sourceColumn: F_06_客户行业

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isText":true}

	partition T02_客户表-dbd3e6f3-ae59-4838-828d-f051c19ebb69 = m
		mode: import
		source =
				let
				  源 = Csv.Document(File.Contents(Path&"\T02_客户表.csv"), [Delimiter = ",", Columns = 7, Encoding = 65001, QuoteStyle = QuoteStyle.None]),
				    提升的标题 = Table.PromoteHeaders(源, [PromoteAllScalars=true]),
				    更改的类型 = Table.TransformColumnTypes(提升的标题,{{"F_00_自动编号", Int64.Type}, {"F_03_客户生日", type date}, {"F_05_注册日期", type date}})
				in
				    更改的类型

	annotation PBI_ResultType = Table

	annotation PBI_NavigationStepName = 导航

