table T03_入库信息表
	lineageTag: 8c1fe0a6-3e8d-4433-a449-ae177a1d067c

	column F_00_自动编号
		dataType: int64
		formatString: 0
		lineageTag: cc716662-d9a2-4ae6-9dc4-e3c5530c8aef
		summarizeBy: sum
		sourceColumn: F_00_自动编号

		annotation SummarizationSetBy = Automatic

	column F_01_入库产品编号
		dataType: string
		lineageTag: fcdf14bf-bf56-445e-89fc-8f03485933df
		summarizeBy: none
		sourceColumn: F_01_入库产品编号

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isText":true}

	column F_02_入库产品数量
		dataType: int64
		formatString: 0
		lineageTag: 9abe56df-87a6-407b-a760-14f453d74df9
		summarizeBy: sum
		sourceColumn: F_02_入库产品数量

		annotation SummarizationSetBy = Automatic

	column F_03_入库门店编号
		dataType: string
		lineageTag: 525eb89e-1fb1-44da-987e-dba836d96f67
		summarizeBy: none
		sourceColumn: F_03_入库门店编号

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isText":true}

	column F_04_入库日期
		dataType: dateTime
		formatString: Long Date
		lineageTag: 41ac8230-cbf1-4b8e-a270-1540a942c051
		summarizeBy: none
		sourceColumn: F_04_入库日期

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Date

	partition T03_入库信息表-64b20158-49ac-4283-a49e-19feffeb4dc8 = m
		mode: import
		source =
				let
				  源 = Csv.Document(File.Contents(Path&"\T03_入库信息表.csv"), [Delimiter = ",", Columns = 5, Encoding = 65001, QuoteStyle = QuoteStyle.None]),
				    提升的标题 = Table.PromoteHeaders(源, [PromoteAllScalars=true]),
				    更改的类型 = Table.TransformColumnTypes(提升的标题,{{"F_00_自动编号", Int64.Type}, {"F_02_入库产品数量", Int64.Type}, {"F_04_入库日期", type date}})
				in
				    更改的类型

	annotation PBI_ResultType = Table

	annotation PBI_NavigationStepName = 导航

