table T06_销售目标表
	lineageTag: ade61361-d28a-4df7-92eb-f9c66bcf88d8

	column F_00_自动编号
		dataType: int64
		formatString: 0
		lineageTag: 3cdf90a8-ff75-409d-868b-5723dde31135
		summarizeBy: sum
		sourceColumn: F_00_自动编号

		annotation SummarizationSetBy = Automatic

	column F_01_省ID
		dataType: int64
		formatString: 0
		lineageTag: cd0dc4ac-859e-4123-a6c1-49da0d3b7443
		summarizeBy: none
		sourceColumn: F_01_省ID

		annotation SummarizationSetBy = Automatic

	column F_02_省简称
		dataType: string
		lineageTag: 3a4f9934-0a4e-41d4-b0a9-e4d6afe2f989
		summarizeBy: none
		sourceColumn: F_02_省简称

		annotation SummarizationSetBy = Automatic

	column F_03_月份
		dataType: dateTime
		formatString: Long Date
		lineageTag: fb3e2b58-512f-4c52-b9ed-aa5321ed1ca5
		summarizeBy: none
		sourceColumn: F_03_月份

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Date

	column F_04_销售目标
		dataType: int64
		formatString: 0
		lineageTag: f8658ac3-24db-4b55-86fc-773b874233ba
		summarizeBy: sum
		sourceColumn: F_04_销售目标

		annotation SummarizationSetBy = Automatic

	partition T06_销售目标表-9c0c1277-9f12-4b9e-a820-ba7d12ddbe47 = m
		mode: import
		source =
				let
				  源 = Csv.Document(File.Contents(Path&"\T06_销售目标表.csv"), [Delimiter = ",", Columns = 5, Encoding = 65001, QuoteStyle = QuoteStyle.None]),
				    提升的标题 = Table.PromoteHeaders(源, [PromoteAllScalars=true]),
				    更改的类型 = Table.TransformColumnTypes(提升的标题,{{"F_00_自动编号", Int64.Type}, {"F_01_省ID", Int64.Type}, {"F_03_月份", type date}, {"F_04_销售目标", Int64.Type}})
				in
				    更改的类型

	annotation PBI_ResultType = Table

	annotation PBI_NavigationStepName = 导航

